name: .NET

on:
  pull_request:
    tags-ignore:
      - '*'
  push:
    tags-ignore:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup .NET Core 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: |
        dotnet restore
        dotnet tool restore
    - name: Lint
      run: |
        dotnet format DotnetArchive.sln --check
        dotnet format DotnetArchive.sln --check --fix-style warn
    - name: Build
      run: |
        dotnet build --no-restore -c Debug
        dotnet build --no-restore -c Release
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --framework netcoreapp3.1
        dotnet test --no-build --verbosity normal --framework net5.0
    - name: Pack
      run: dotnet pack --no-restore -c Release
    - uses: actions/upload-artifact@v2
      with:
        name: DotnetArchiveOutput
        path: DotnetArchive/nupkg/*.nupkg
